let personData = {"ednaMode":{ "name": "Edna Mode",
"dob": "05/11/2004",
"movie": "The Incredibles",
"imageurl": "/images/edna.jpg",
"height": "129cm",
"hobbies": ["Fashion", "Superheros", "Design"]},

"babyYoda" : { "name": "Baby Yoda",
"dob": "12/11/2019",
"movie": "Star Wars Mandalorian",
"imageurl": "/images/babyYoda.jpg",
"height": "60cm",
"hobbies": ["Telekinesis", "Been Cute", "Macaroons"]},

"dipper" : { "name": "Dipper",
"dob": "01/01/2012",
"movie": "Gravity Falls",
"imageurl": "/images/dipper.png",
"height": "152cm",
"hobbies": ["Exploring", "Mysteries", "Sleeping"]},

"fluffo" : { "name": "Fluffo",
"dob": "01/02/2021",
"movie": "none",
"imageurl": "/images/fluffo.jpg",
"height": "20cm",
"hobbies": ["Sleeping", "Eating", "Lurking"]},

"mckitty" : { "name": "McKitty",
"dob": "01/02/2021",
"movie": "none",
"imageurl": "/images/kittynom.jpg",
"height": "20cm",
"hobbies": ["Staring At Fries", "Eating Fries", "Robbing fries"]},
};